import { Project } from '@/types/project.types';

export const projects: Project[] = [
  {
    id: '1',
    slug: 'ai-saas-dashboard',
    title: 'AI SaaS Analytics Dashboard',
    tagline: 'Real-time AI-powered business intelligence platform with GPT-4 insights',
    category: 'ai',
    status: 'live',
    featured: true,
    thumbnail: '/images/projects/ai-saas.jpg',
    screenshots: ['/images/projects/ai-saas.jpg'],
    businessProblem:
      'Mid-sized businesses struggled to extract actionable insights from their scattered data across multiple tools — CRM, ERP, and marketing platforms. Manual reporting took 3–4 days per cycle.',
    solution:
      'Built a unified SaaS dashboard that aggregates data from multiple APIs, runs AI analysis using GPT-4, and delivers real-time natural-language insights. Reduced reporting time from days to seconds.',
    features: [
      'Natural language query interface powered by GPT-4',
      'Real-time data sync from 15+ integrations (Salesforce, HubSpot, Stripe)',
      'Automated weekly AI-generated reports via email',
      'Custom KPI builder with drag-and-drop widgets',
      'Role-based access control (RBAC)',
      'Export to PDF, Excel, and Notion',
    ],
    techStack: ['Next.js', 'TypeScript', 'Python', 'FastAPI', 'OpenAI GPT-4', 'LangChain', 'PostgreSQL', 'Redis', 'AWS', 'Docker'],
    githubUrl: 'https://github.com/vamsikrishna/ai-saas-dashboard',
    liveUrl: 'https://ai-dashboard.vamsikrishna.dev',
    challengesFaced: [
      'Handling real-time streaming responses from GPT-4 to the frontend',
      'Optimizing PostgreSQL queries for sub-100ms dashboard loads',
      'Building a rate-limiting strategy to control OpenAI API costs',
    ],
    lessonsLearned: [
      'Server-Sent Events (SSE) are ideal for streaming AI responses',
      'Redis caching dramatically reduces database load for repeated queries',
      'Prompt engineering dramatically improves insight quality',
    ],
    completedAt: '2024-11',
    duration: '3 months',
    clientName: 'TechVentures Corp',
  },
  {
    id: '2',
    slug: 'erp-management-system',
    title: 'Enterprise ERP Management System',
    tagline: 'Full-featured ERP system for manufacturing with inventory, HR & finance modules',
    category: 'erp',
    status: 'live',
    featured: true,
    thumbnail: '/images/projects/erp-system.jpg',
    screenshots: ['/images/projects/erp-system.jpg'],
    businessProblem:
      'A manufacturing company with 500+ employees relied on Excel sheets and 5 separate legacy systems for HR, inventory, payroll, and finance — causing data inconsistencies and costing 20+ hours per week in manual reconciliation.',
    solution:
      'Delivered a unified ERP platform with real-time modules for HR, inventory management, payroll, finance, and production planning. Integrated with existing SAP instance via REST APIs.',
    features: [
      'HR module: employee management, attendance, leave tracking',
      'Inventory: real-time stock tracking, low-stock alerts, supplier orders',
      'Payroll: automated salary computation with tax deductions',
      'Finance: P&L, balance sheet, expense tracking',
      'Production planning: job orders, machine scheduling',
      'Multi-branch support with role-based permissions',
    ],
    techStack: ['React', 'Node.js', 'Express', 'PostgreSQL', 'Redis', 'Docker', 'AWS EC2', 'Nginx'],
    githubUrl: 'https://github.com/vamsikrishna/erp-system',
    challengesFaced: [
      'Migrating 5 years of data from legacy Excel and SQL Server databases',
      'Designing a permission system with 20+ roles across 3 branches',
      'Real-time synchronization between modules without race conditions',
    ],
    lessonsLearned: [
      'Event-driven architecture with message queues prevents data inconsistencies',
      'Incremental migration with rollback plans is essential for large data moves',
      'Deep domain knowledge of manufacturing processes is critical before coding',
    ],
    completedAt: '2024-08',
    duration: '6 months',
    clientName: 'ManufactureX Industries',
  },
  {
    id: '3',
    slug: 'ai-chatbot-platform',
    title: 'AI Chatbot Platform',
    tagline: 'No-code chatbot builder with GPT-4, RAG, and multi-channel deployment',
    category: 'ai',
    status: 'live',
    featured: true,
    thumbnail: '/images/projects/chatbot-platform.jpg',
    screenshots: ['/images/projects/chatbot-platform.jpg'],
    businessProblem:
      'E-commerce and support teams spent 60% of agent time on repetitive FAQs. Existing chatbot solutions were rigid, required coding, and couldn\'t leverage private company knowledge bases.',
    solution:
      'Developed a no-code chatbot platform with RAG (Retrieval-Augmented Generation) that ingests company documents, websites, and FAQs to create intelligent, context-aware bots deployable on WhatsApp, Slack, and web.',
    features: [
      'Drag-and-drop bot flow builder (no-code)',
      'RAG pipeline: PDF, URL, and text document ingestion',
      'GPT-4 with memory and context window management',
      'Multi-channel: Web widget, WhatsApp, Slack, Telegram',
      'Analytics: conversations, resolution rate, satisfaction score',
      'Human handoff when confidence threshold is low',
    ],
    techStack: ['Next.js', 'Python', 'LangChain', 'OpenAI', 'Pinecone', 'Supabase', 'WhatsApp Business API', 'Docker'],
    githubUrl: 'https://github.com/vamsikrishna/ai-chatbot-platform',
    liveUrl: 'https://chatbot.vamsikrishna.dev',
    challengesFaced: [
      'Chunking and embedding large documents for accurate vector search',
      'Managing conversation context across multi-turn dialogues',
      'Building a visual flow builder from scratch without a library',
    ],
    lessonsLearned: [
      'Chunk overlap in RAG improves retrieval accuracy significantly',
      'HNSW indexing in Pinecone is 10x faster than brute-force for >100k vectors',
      'Confidence scoring prevents hallucinations in production chatbots',
    ],
    completedAt: '2025-01',
    duration: '4 months',
    clientName: 'RetailPro Solutions',
  },
  {
    id: '4',
    slug: 'ecommerce-platform',
    title: 'Full-Stack E-Commerce Platform',
    tagline: 'Scalable multi-vendor marketplace with real-time inventory and payments',
    category: 'fullstack',
    status: 'live',
    featured: false,
    thumbnail: '/images/projects/ecommerce.jpg',
    screenshots: ['/images/projects/ecommerce.jpg'],
    businessProblem: 'A retail brand needed a custom e-commerce platform to handle 50,000+ SKUs, multi-vendor management, and real-time inventory across 10 warehouses.',
    solution: 'Built a performant multi-vendor e-commerce platform with Next.js App Router, server-side rendering for SEO, Stripe payments, and a real-time inventory sync system.',
    features: [
      'Multi-vendor marketplace with seller dashboards',
      'Real-time inventory sync across 10 warehouses',
      'Stripe payment gateway with subscription support',
      'Advanced product filtering and search (Algolia)',
      'Order tracking with live status updates',
      'SEO-optimized product pages (90+ Lighthouse score)',
    ],
    techStack: ['Next.js', 'TypeScript', 'Node.js', 'PostgreSQL', 'Stripe', 'Algolia', 'Redis', 'Cloudinary', 'Vercel'],
    githubUrl: 'https://github.com/vamsikrishna/ecommerce-platform',
    liveUrl: 'https://shop.vamsikrishna.dev',
    challengesFaced: [
      'Optimizing 50,000+ product pages with ISR without hitting build limits',
      'Implementing real-time inventory updates without polling',
    ],
    lessonsLearned: [
      'On-demand ISR revalidation is perfect for large product catalogs',
      'WebSocket connections for inventory updates improve UX dramatically',
    ],
    completedAt: '2024-06',
    duration: '5 months',
  },
  {
    id: '5',
    slug: 'automation-workflow',
    title: 'Business Process Automation Suite',
    tagline: 'n8n-powered automation workflows saving 200+ hours per month',
    category: 'automation',
    status: 'live',
    featured: false,
    thumbnail: '/images/projects/automation.jpg',
    screenshots: ['/images/projects/automation.jpg'],
    businessProblem: 'A digital marketing agency was manually processing leads from 10+ sources, sending proposals, and updating CRM — consuming 40+ hours per week.',
    solution: 'Designed and deployed a suite of automation workflows using n8n, Zapier, and custom Node.js scripts that handle the entire lead-to-proposal pipeline automatically.',
    features: [
      'Automated lead capture from forms, email, and social media',
      'AI-powered lead scoring and qualification',
      'Automated proposal generation using templates + GPT-4',
      'CRM auto-update (HubSpot integration)',
      'Slack notifications for high-priority leads',
      'Weekly analytics report generation and email delivery',
    ],
    techStack: ['Node.js', 'n8n', 'Python', 'OpenAI', 'HubSpot API', 'SendGrid', 'PostgreSQL', 'Docker'],
    githubUrl: 'https://github.com/vamsikrishna/automation-suite',
    challengesFaced: [
      'Handling webhook failures and ensuring idempotent processing',
      'Parsing unstructured email content for lead data extraction',
    ],
    lessonsLearned: [
      'Dead-letter queues are essential for reliable webhook processing',
      'LLMs excel at unstructured data extraction when given few-shot examples',
    ],
    completedAt: '2024-03',
    duration: '2 months',
  },
  {
    id: '6',
    slug: 'realtime-dashboard',
    title: 'Real-Time Analytics Dashboard',
    tagline: 'WebSocket-powered live metrics dashboard for SaaS monitoring',
    category: 'frontend',
    status: 'live',
    featured: false,
    thumbnail: '/images/projects/dashboard.jpg',
    screenshots: ['/images/projects/dashboard.jpg'],
    businessProblem: 'A SaaS startup needed a real-time monitoring dashboard for their platform showing live user activity, server metrics, and revenue KPIs.',
    solution: 'Built a stunning real-time dashboard using Next.js, Recharts, and WebSockets that updates every second with live data from multiple microservices.',
    features: [
      'Real-time charts updating via WebSocket',
      'Custom chart components built with Recharts + D3',
      'Dark/light mode with theme persistence',
      'Exportable reports in PDF and CSV',
      'Alert system with configurable thresholds',
    ],
    techStack: ['Next.js', 'TypeScript', 'Recharts', 'D3.js', 'WebSockets', 'Node.js', 'Redis', 'Tailwind CSS'],
    githubUrl: 'https://github.com/vamsikrishna/realtime-dashboard',
    liveUrl: 'https://dashboard.vamsikrishna.dev',
    challengesFaced: ['Managing WebSocket reconnections gracefully', 'Rendering 1000+ data points without performance degradation'],
    lessonsLearned: ['Canvas-based rendering outperforms SVG for dense data visualizations', 'Virtual scrolling is essential for large tabular data'],
    completedAt: '2023-12',
    duration: '2 months',
  },
];
