import { Service } from '@/types';

export const services: Service[] = [
  {
    id: 'ai-solutions',
    title: 'AI & Machine Learning Solutions',
    description:
      'Transform your business with custom AI integrations — chatbots, recommendation systems, document intelligence, and predictive analytics powered by GPT-4, LangChain, and RAG pipelines.',
    icon: 'Brain',
    features: [
      'Custom GPT-4 / LLM integrations',
      'RAG pipelines with vector databases',
      'AI chatbots for customer support',
      'Document intelligence & extraction',
      'Predictive analytics dashboards',
      'LLM fine-tuning & prompt engineering',
    ],
    techUsed: ['OpenAI GPT-4', 'LangChain', 'Pinecone', 'Python', 'FastAPI', 'Next.js'],
    cta: 'Build AI Solution',
    highlighted: true,
    price: 'Starting at ₹80,000',
    deliveryTime: '4–8 weeks',
  },
  {
    id: 'fullstack-development',
    title: 'Full-Stack Web Applications',
    description:
      'End-to-end web application development from architecture to deployment. Premium UI/UX, scalable backend, database design, and production-grade DevOps — all under one roof.',
    icon: 'Code2',
    features: [
      'Next.js / React frontend with stunning UI',
      'Node.js / Python backend APIs',
      'Database design (PostgreSQL, MongoDB)',
      'Authentication & authorization',
      'Third-party API integrations',
      'Vercel / AWS deployment & CI/CD',
    ],
    techUsed: ['Next.js', 'React', 'Node.js', 'TypeScript', 'PostgreSQL', 'Docker', 'AWS'],
    cta: 'Start Your Project',
    highlighted: false,
    price: 'Starting at ₹60,000',
    deliveryTime: '6–12 weeks',
  },
  {
    id: 'erp-development',
    title: 'ERP & Business Systems',
    description:
      'Custom Enterprise Resource Planning systems designed for your business workflows — inventory, HR, payroll, finance, and production modules built for scale and reliability.',
    icon: 'Building2',
    features: [
      'HR & payroll management modules',
      'Inventory & supply chain tracking',
      'Financial reporting & dashboards',
      'Multi-branch & multi-role support',
      'Legacy system migration & integration',
      'SAP / Tally integration APIs',
    ],
    techUsed: ['React', 'Node.js', 'PostgreSQL', 'Redis', 'Docker', 'AWS EC2'],
    cta: 'Discuss ERP Needs',
    highlighted: false,
    price: 'Starting at ₹1,50,000',
    deliveryTime: '12–24 weeks',
  },
  {
    id: 'automation',
    title: 'Business Process Automation',
    description:
      'Eliminate repetitive work with intelligent automation. From lead generation to reporting, I build workflows that run on autopilot — saving hours every day.',
    icon: 'Zap',
    features: [
      'n8n & Zapier workflow automation',
      'CRM & email automation pipelines',
      'AI-powered lead qualification',
      'Automated reporting systems',
      'Webhook & API integration workflows',
      'Scheduled data sync & ETL pipelines',
    ],
    techUsed: ['n8n', 'Python', 'Node.js', 'OpenAI', 'HubSpot', 'Zapier', 'PostgreSQL'],
    cta: 'Automate My Business',
    highlighted: false,
    price: 'Starting at ₹30,000',
    deliveryTime: '2–4 weeks',
  },
  {
    id: 'api-development',
    title: 'Backend API Development',
    description:
      'Robust, secure, and scalable REST & GraphQL APIs built with best practices — proper authentication, rate limiting, documentation, and monitoring included.',
    icon: 'Server',
    features: [
      'RESTful & GraphQL API design',
      'JWT / OAuth 2.0 authentication',
      'Rate limiting & API security',
      'OpenAPI / Swagger documentation',
      'API monitoring & alerting',
      'Microservices architecture',
    ],
    techUsed: ['Node.js', 'Express', 'Python', 'FastAPI', 'PostgreSQL', 'Redis', 'Docker'],
    cta: 'Build My API',
    highlighted: false,
    price: 'Starting at ₹40,000',
    deliveryTime: '3–6 weeks',
  },
  {
    id: 'dashboard-development',
    title: 'Analytics & Dashboard Development',
    description:
      'Beautiful, data-rich dashboards and admin panels that give you real-time visibility into your business metrics. Interactive charts, live updates, and clean data visualizations.',
    icon: 'BarChart3',
    features: [
      'Real-time data visualization',
      'Custom chart components (Recharts, D3)',
      'Admin panels with CRUD operations',
      'KPI tracking & alert systems',
      'Export to PDF, Excel, CSV',
      'Mobile-responsive layouts',
    ],
    techUsed: ['Next.js', 'React', 'Recharts', 'D3.js', 'TypeScript', 'Supabase', 'Tailwind CSS'],
    cta: 'Create Dashboard',
    highlighted: false,
    price: 'Starting at ₹35,000',
    deliveryTime: '3–5 weeks',
  },
];
